import type { Metadata } from 'next'
import '@/app/globals.css'
import '@/styles/animation.scss'
import '@/styles/globals.scss'
import '@/styles/highlight.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
